/**
 * TypeScript Config Generator for @piikeep/web-help
 * Generates help.config.ts files with type safety
 * @module @piikeep/web-help/devtools/configGenerator
 */

import type { ConfigGeneratorOptions, GeneratedConfig } from './types';

// ============================================================================
// Default Configuration Values
// ============================================================================

const DEFAULT_OPTIONS: Required<ConfigGeneratorOptions> = {
  projectName: 'my-help-docs',
  contentPath: './help-content',
  formats: ['md'],
  storage: {
    type: 'localStorage',
    prefix: 'help_',
  },
  search: {
    enabled: true,
    type: 'client',
    threshold: 0.3,
  },
  media: {
    lazyLoad: true,
    lightbox: true,
    cdnBaseUrl: undefined as unknown as string,
  },
  navigation: {
    showTOC: true,
    showBreadcrumbs: true,
    showPagination: true,
  },
  outputFormat: 'typescript',
};

// ============================================================================
// Config Generation Functions
// ============================================================================

/**
 * Generates a TypeScript help configuration file
 * 
 * @param options - Configuration options
 * @returns Generated configuration content and metadata
 * 
 * @example
 * ```typescript
 * const result = generateConfig({
 *   projectName: 'my-app-docs',
 *   contentPath: './docs',
 *   formats: ['md', 'mdx'],
 * });
 * 
 * // Write result.content to help.config.ts
 * ```
 */
export function generateConfig(options: ConfigGeneratorOptions = {}): GeneratedConfig {
  const config = { ...DEFAULT_OPTIONS, ...options };
  const warnings: string[] = [];

  // Validate options
  if (config.formats.length === 0) {
    warnings.push('No content formats specified, defaulting to markdown');
    config.formats = ['md'];
  }

  if (config.search.enabled && config.search.type === 'custom' && !config.search.threshold) {
    warnings.push('Custom search adapter selected but no threshold specified');
  }

  const isTypeScript = config.outputFormat === 'typescript';
  const filename = isTypeScript ? 'help.config.ts' : 'help.config.js';

  const content = isTypeScript
    ? generateTypeScriptConfig(config)
    : generateJavaScriptConfig(config);

  return {
    content,
    filename,
    warnings: warnings.length > 0 ? warnings : undefined,
  };
}

/**
 * Generates TypeScript configuration content
 */
function generateTypeScriptConfig(config: Required<ConfigGeneratorOptions>): string {
  return `/**
 * Help System Configuration
 * Generated by @piikeep/web-help config generator
 * 
 * @see https://github.com/pii-keep/web-help for documentation
 */
import type { HelpConfig } from '@piikeep/web-help';

/**
 * Configuration for ${config.projectName}
 */
const helpConfig: HelpConfig = {
  /**
   * Content configuration
   */
  content: {
    // Content source type: 'static' for bundled files, 'api' for remote content
    source: 'static',
    
    // Base path to content directory
    basePath: '${config.contentPath}',
    
    // Supported content formats
    formats: ${JSON.stringify(config.formats)},
  },

  /**
   * Storage configuration for user preferences
   */
  storage: {
    // Storage type: 'localStorage', 'sessionStorage', 'cookies', 'memory', or 'custom'
    type: '${config.storage.type}',
    
    // Prefix for storage keys
    prefix: '${config.storage.prefix || 'help_'}',
  },

  /**
   * Search configuration
   */
  search: {
    // Enable/disable search functionality
    enabled: ${config.search.enabled},
    
    // Search type: 'client' for built-in fuse.js, 'custom' for custom adapter
    type: '${config.search.type}',
    
    // Search options
    options: {
      // Fuzzy matching threshold (0 = exact, 1 = match anything)
      threshold: ${config.search.threshold},
      
      // Fields to search
      keys: ['title', 'content', 'tags', 'description'],
    },
  },

  /**
   * Media handling configuration
   */
  media: {
    images: {
      // Enable lazy loading for images
      loading: ${config.media.lazyLoad ? "'lazy'" : "'eager'"},
      
      // Enable lightbox for image viewing
      lightbox: ${config.media.lightbox},
      ${config.media.cdnBaseUrl ? `
      // CDN configuration
      cdn: {
        baseUrl: '${config.media.cdnBaseUrl}',
      },` : ''}
    },
    videos: {
      // Enable lazy loading for videos
      lazyLoad: ${config.media.lazyLoad},
      
      // Supported video providers
      providers: ['youtube', 'vimeo'],
    },
  },

  /**
   * Navigation configuration
   */
  navigation: {
    // Show table of contents
    showTOC: ${config.navigation.showTOC},
    
    // Show breadcrumb navigation
    showBreadcrumbs: ${config.navigation.showBreadcrumbs},
    
    // Show previous/next pagination
    showPagination: ${config.navigation.showPagination},
  },
};

export default helpConfig;
`;
}

/**
 * Generates JavaScript configuration content
 */
function generateJavaScriptConfig(config: Required<ConfigGeneratorOptions>): string {
  return `/**
 * Help System Configuration
 * Generated by @piikeep/web-help config generator
 * 
 * @see https://github.com/pii-keep/web-help for documentation
 */

/** @type {import('@piikeep/web-help').HelpConfig} */
const helpConfig = {
  /**
   * Content configuration
   */
  content: {
    // Content source type: 'static' for bundled files, 'api' for remote content
    source: 'static',
    
    // Base path to content directory
    basePath: '${config.contentPath}',
    
    // Supported content formats
    formats: ${JSON.stringify(config.formats)},
  },

  /**
   * Storage configuration for user preferences
   */
  storage: {
    // Storage type: 'localStorage', 'sessionStorage', 'cookies', 'memory', or 'custom'
    type: '${config.storage.type}',
    
    // Prefix for storage keys
    prefix: '${config.storage.prefix || 'help_'}',
  },

  /**
   * Search configuration
   */
  search: {
    // Enable/disable search functionality
    enabled: ${config.search.enabled},
    
    // Search type: 'client' for built-in fuse.js, 'custom' for custom adapter
    type: '${config.search.type}',
    
    // Search options
    options: {
      // Fuzzy matching threshold (0 = exact, 1 = match anything)
      threshold: ${config.search.threshold},
      
      // Fields to search
      keys: ['title', 'content', 'tags', 'description'],
    },
  },

  /**
   * Media handling configuration
   */
  media: {
    images: {
      // Enable lazy loading for images
      loading: ${config.media.lazyLoad ? "'lazy'" : "'eager'"},
      
      // Enable lightbox for image viewing
      lightbox: ${config.media.lightbox},
      ${config.media.cdnBaseUrl ? `
      // CDN configuration
      cdn: {
        baseUrl: '${config.media.cdnBaseUrl}',
      },` : ''}
    },
    videos: {
      // Enable lazy loading for videos
      lazyLoad: ${config.media.lazyLoad},
      
      // Supported video providers
      providers: ['youtube', 'vimeo'],
    },
  },

  /**
   * Navigation configuration
   */
  navigation: {
    // Show table of contents
    showTOC: ${config.navigation.showTOC},
    
    // Show breadcrumb navigation
    showBreadcrumbs: ${config.navigation.showBreadcrumbs},
    
    // Show previous/next pagination
    showPagination: ${config.navigation.showPagination},
  },
};

module.exports = helpConfig;
`;
}

/**
 * Generates a minimal configuration for quick start
 */
export function generateMinimalConfig(options: {
  contentPath?: string;
  typescript?: boolean;
} = {}): GeneratedConfig {
  const { contentPath = './help-content', typescript = true } = options;
  
  const filename = typescript ? 'help.config.ts' : 'help.config.js';
  
  const content = typescript
    ? `import type { HelpConfig } from '@piikeep/web-help';

const helpConfig: HelpConfig = {
  content: {
    source: 'static',
    basePath: '${contentPath}',
  },
};

export default helpConfig;
`
    : `/** @type {import('@piikeep/web-help').HelpConfig} */
const helpConfig = {
  content: {
    source: 'static',
    basePath: '${contentPath}',
  },
};

module.exports = helpConfig;
`;

  return { content, filename };
}

/**
 * Validates a configuration object
 */
export function validateConfigOptions(options: ConfigGeneratorOptions): {
  valid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Check content path
  if (options.contentPath && options.contentPath.includes('..')) {
    warnings.push('Content path contains relative parent paths, ensure this is intentional');
  }

  // Check formats
  if (options.formats) {
    const validFormats = ['md', 'mdx', 'json', 'csv'];
    const invalidFormats = options.formats.filter(f => !validFormats.includes(f));
    if (invalidFormats.length > 0) {
      errors.push(`Invalid content formats: ${invalidFormats.join(', ')}`);
    }
  }

  // Check storage type
  if (options.storage?.type) {
    const validTypes = ['localStorage', 'sessionStorage', 'cookies', 'memory', 'custom'];
    if (!validTypes.includes(options.storage.type)) {
      errors.push(`Invalid storage type: ${options.storage.type}`);
    }
  }

  // Check search threshold
  if (options.search?.threshold !== undefined) {
    if (options.search.threshold < 0 || options.search.threshold > 1) {
      errors.push('Search threshold must be between 0 and 1');
    }
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// ============================================================================
// Exports
// ============================================================================

export const configGenerator = {
  generateConfig,
  generateMinimalConfig,
  validateConfigOptions,
};

export default configGenerator;
